### PR TITLE
Remove unneeded features and refactor

### PR DESCRIPTION
**Pull request by noClaps**
- [x] I have tested my changes on my device and it is working.
- [x] I am not using insecure packages.
- [x] I am not adding malicious code that may harm the privacy or security of the reader.

### CODE REVIEW

**Comment by noClaps** [comment]
@MesterMan03 Can you test if the theme toggle and scroll to top buttons are working correctly on your devices? Also can you make sure that the posts still look correct?

**Review by MesterMan03 — COMMENTED** [review]
I'm not sure if the RGB links are a good idea for accessibility. Otherwise it's a nice redesign.

**Comment by noClaps** [comment]
That's a good point. I've been thinking about if I actually wanna have it that way and I might change it to be something else.

**Review by MesterMan03 — APPROVED** [review]
LPTM (Looks Professional To Me)

**Pull request merged**
